apiVersion: v1
kind: Pod
metadata:
        name: mypod
        labels:
             app: dev  
spec:
         containers:
            - name: mynginx
              image: nginx
              ports:
                - containerPort: 80
              resources:
                      requests:
                              cpu: 800m
                              memory: 100Mi
                      limits:
                              cpu: 900m
                              memory: 300Mi        
